import { FaYoutube } from "react-icons/fa";
//import Link from "next/link";
import Link from '@/components/Link';
import { CheckIcon } from "@heroicons/react/24/solid";
import CookieConsent from "@/components/CookieConsent";

const Footer = () => (
    <footer className="bg-gray-800 text-white p-4 mt-8">
        <div className="container mx-auto flex flex-col md:flex-row justify-between items-start">
            <div className="mb-4 md:mb-0 min-w-[10em] px-4 mt-2">
                <div className="flex items-center">
                    <FaYoutube className="text-3xl md:text-2xl text-red-200 inline-block mr-2" />
                    <span className="text-lg md:text-base font-semibold">
                        Videyo
                    </span>
                </div>

                <ul className="space-y-2 py-2">
                    <li>
                        <Link
                            href="/"
                            className="text-sm text-gray-400 hover:text-white transition duration-300 ease-in-out">
                            Homepage
                        </Link>
                    </li>
                    <li>
                        <Link
                            href="/best"
                            className="text-sm text-gray-400 hover:text-white transition duration-300 ease-in-out">
                            Best By Date
                        </Link>
                    </li>
                    <li>
                        <Link
                            title="video listing in the style nostalgic style of bestofyoutube.com"
                            href="/boyt"
                            className="text-sm text-gray-400 hover:text-white transition duration-300 ease-in-out">
                            BOYT
                        </Link>
                    </li>
                    <li>
                        <Link
                            href="/terms"
                            className="text-sm text-gray-400 hover:text-white transition duration-300 ease-in-out">
                            Terms of Service
                        </Link>
                    </li>
                    <li>
                        <Link
                            href="/privacy"
                            className="text-sm text-gray-400 hover:text-white transition duration-300 ease-in-out">
                            Privacy Policy
                        </Link>
                    </li>
                </ul>
            </div>

            <div className="px-4 text-md mb-4">
                <h2 className="text-2xl font-semibold mb-4">What is Videyo?</h2>
                <p className="text-gray-400">
                    Videyo is an automatically curated collection of YouTube
                    videos that may or may not be worth a watch.
                </p>
                <br />
                <p className="text-gray-400">
                    Descriptions are generated by AI. The goal is to give you a
                    sense of what the video is about and what type of video it
                    is. Ideally you can figure out if the video is for you
                    before you click it.
                </p>
            </div>

            <div className="px-4  mb-4">
                <h2 className="text-2xl font-semibold mb-4">
                    Why was Videyo created?
                </h2>

                <div className="space-y-4 text-gray-400">
                    <div className="flex items-start">
                        <CheckIcon className="h-6 w-6 sm:h-5 sm:w-5 mr-3 sm:mr-2 text-green-500 flex-shrink-0" />
                        <div>
                            <span className="font-bold">No clickbait</span> - we
                            try to standardize titles and descriptions, so you
                            know what the video is actually about.
                        </div>
                    </div>

                    <div className="flex items-start">
                        <CheckIcon className="h-6 w-6 sm:h-5 sm:w-5 mr-3 sm:mr-2 text-green-500 flex-shrink-0" />
                        <div>
                            <span className="font-bold">
                                Discover what&apos;s trending...
                            </span>{" "}
                            Videyo&apos;s curated collection and AI-powered
                            descriptions help you quickly find videos worth
                            watching.
                        </div>
                    </div>

                    <div className="flex items-start">
                        <CheckIcon className="h-6 w-6 sm:h-5 sm:w-5 mr-3 sm:mr-2 text-green-500 flex-shrink-0" />
                        <div>
                            <span className="font-bold">
                                ... and hidden gems.
                            </span>{" "}
                            We give you those videos that might have otherwise
                            slipped through the cracks of YouTube&apos;s vast
                            algorithm.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <p className="text-gray-400 mt-2 text-center text-sm">
            © 2024 <a href="mailto:alex@videyo.com">Alex W</a>. Hi Frank!
        </p>
        <CookieConsent />
    </footer>
);

export default Footer;
